### ISSUE TITLE
No cleanup method

### ISSUE THREAD

**Issue by JoelCodes** [third774/image-focus#4]
I wanted to use this method with some React components, but there's no cleanup methods.  In other words, there's 8 calls to `addEventListener` in the constructor, but no cleanup method that would call `removeEventListener`.

**Comment by JoelCodes** [comment]
This is localized to the FocusPicker, it seems.  The FocusedImage seems to have good cleanup.

**Comment by third774** [comment]
Ah! Cool — I'll try to get a fix out for this soon! Thanks for reporting!

**Comment by third774** [comment]
Just published `1.1.0`
